[package]
name = "husky-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
smallvec.workspace = true
# abstractions
small-cell-stack = { path = "../../abstractions/small-cell-stack" }
enum-class.workspace = true
salsa.workspace = true
# fs
husky-vfs.workspace = true
# linkage
husky-linkage.workspace = true
husky-linkage-impl.workspace = true
# protocols
husky-visual-protocol.workspace = true
husky-trace-protocol.workspace = true
