[package]
name = "husky-sem-var-deps"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
# abstractions
propagate.workspace = true
graph-dynamics.workspace = true
salsa.workspace = true
vec-like.workspace = true
# kernel
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
husky-term-prelude.workspace = true
# semantics
husky-sem-expr.workspace = true
husky-sem-item-path-deps.workspace = true
husky-sem-static-mut-deps.workspace = true
# syntax
husky-syn-expr.workspace = true
husky-entity-tree.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# fs
husky-manifest.workspace = true
husky-corgi-config.workspace = true
husky-vfs.workspace = true
# kernel
husky-dec-signature.workspace = true
husky-eth-signature.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-entity-path.workspace = true
husky-coword.workspace = true
husky-expr.workspace = true
husky-place.workspace = true
# lex
husky-toml-token.workspace = true
husky-token.workspace = true
husky-text.workspace = true
husky-token-data.workspace = true
husky-regional-token.workspace = true
# syntax
husky-opr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
husky-syn-opr.workspace = true
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-entity-tree = { workspace = true, features = ["test_utils"] }
husky-corgi-config-ast.workspace = true
# semantics
husky-sem-expr.workspace = true

[lints]
workspace = true
