[package]
name = "usage-cap"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
lazy_static.workspace = true
thiserror.workspace = true
tokio.workspace = true
# utils
husky-print-utils.workspace = true

[lints]
workspace = true
