[package]
name = "husky-file"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"

[lib]
doctest = false

[dependencies]
rustc-hash = "1.1.0"
itertools = "^0.10.3"
lsp-types = { version = "0.93", features = ["proposed"] }
indexmap = "1.8.1"
salsa = "0.17.0-pre.2"
interner = { path = "../../abstraction/interner" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }
sync-utils = { path = "../../utils/husky-sync-utils" }
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-path-utils = { path = "../../utils/husky-path-utils" }
husky-word = { path = "../../concept/husky-word" }
