[package]
name = "visored-annotation"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
lazy_static.workspace = true
# abstractions
enum-class.workspace = true
salsa.workspace = true
# latex
latex-prelude.workspace = true
latex-token.workspace = true
latex-ast.workspace = true
latex-command = { workspace = true, optional = true }
# protocols
husky-text-protocol.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
# abstractions
salsa.workspace = true
# kernel
husky-coword.workspace = true
# latex
latex-command.workspace = true
# visored
visored-sem-expr = { workspace = true, features = ["test_helpers"] }

[lints]
workspace = true

[features]
test_helpers = ["dep:latex-command"]
