[package]
edition = "2021"
name = "husky-package-semantics"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
salsa = "0.17.0-pre.2"
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-word = { path = "../../syntax/husky-word" }
fold = { path = "../../abstraction/fold" }
husky-vm = { path = "../../vm/husky-vm" }
husky-entity-route = { path = "../../concept/husky-entity-route" }
husky-entity-syntax = { path = "../../syntax/husky-entity-syntax" }
husky-file = { path = "../../syntax/husky-file" }
husky-text = { path = "../../syntax/husky-text" }
husky-ast = { path = "../../syntax/husky-ast" }
husky-semantics-error = { path = "../husky-semantics-error" }
husky-eager-semantics = { path = "../husky-eager-semantics" }
husky-entity-semantics = { path = "../husky-entity-semantics" }
