[package]
name = "husky-syn-opr"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# abstractions
enum-class.workspace = true
# lex
husky-text-protocol.workspace = true
# kernel
husky-coword.workspace = true
husky-opr = { path = "../../kernel/husky-opr" }
# utils
husky-print-utils = { path = "../../utils/husky-print-utils" }
