wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725957302
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
