[package]
name = "husky-mono-linktime"
version.workspace = true
edition = "2021"

[dependencies]
dashmap.workspace = true
smallvec.workspace = true
libloading.workspace = true
fxhash.workspace = true
similar.workspace = true
# abstractions
salsa.workspace = true
version-stamp.workspace = true
vec-like.workspace = true
# comptime
husky-rust-transpilation.workspace = true
# fs
husky-manifest.workspace = true
husky-corgi-config.workspace = true
husky-vfs.workspace = true
# kernel
husky-item-path-interface.workspace = true
husky-standard-value.workspace = true
husky-devsoul.workspace = true
# linket
husky-linket.workspace = true
husky-linket-impl.workspace = true
husky-any-linket-impls.workspace = true
# linktime
husky-linktime.workspace = true
# devsoul
husky-devsoul-interface.workspace = true
# utils
husky-cargo-utils.workspace = true
husky-print-utils.workspace = true

[dev-dependencies]
# devsoul
husky-standard-devsoul-interface.workspace = true
# comptime
husky-dev-comptime.workspace = true
husky-vfs = { workspace = true, features = ["test_utils"] }
# linket
husky-standard-linket-impl.workspace = true
