[workspace]
members = [
    "crates/abstraction/*",
    "crates/apps/*",
    "crates/comptime/*",
    "crates/devtools/*",
    "crates/ide/*",
    "crates/infer/*",
    "crates/kernel/*",
    "crates/runtime/*",
    "crates/semantics/*",
    "crates/static/husky-root-static-defn",
    "crates/static/husky-static-defn",
    "crates/static/domains/ml/*",
    "crates/static/__husky",
    "crates/static/husky-static-defn",
    "crates/static/husky-static-visualizer",
    "crates/syntax/*",
    "crates/devtime/*",
    "crates/try/*",
    "crates/utils/*",
    "crates/vm/*",
    "crates/benchmarks/*"
]
exclude = ["crates/gui"]
resolver = "2"

[profile.dev]
opt-level = 1
panic = "unwind"

[profile.test]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
