[package]
name = "husky-symbol-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
once_cell = "1.16.0"
# abstraction
vec-like = { path = "../../abstraction/vec-like" }
local-stack = { path = "../../abstraction/local-stack" }
salsa = { path = "../../abstraction/salsa" }
# fs
husky-vfs = { path = "../../fs/husky-vfs" }
# kernel
husky-entity-path = { path = "../../kernel/husky-entity-path" }
husky-word = { path = "../../kernel/husky-word" }
# lex
husky-text = { path = "../../lex/husky-text" }
# syntax
husky-entity-tree = { path = "../../syntax/husky-entity-tree" }
