[package]
name = "husky-code-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ecolor.workspace = true
# abstractions
enum-index = { path = "../../abstractions/enum-index" }
# gui
# protocols
husky-token-protocol = { path = "../../protocols/husky-token-protocol" }
# utils
