[package]
name = "husky-layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
salsa = "0.17.0-pre.2"
husky-entity-route = { path = "../../concept/husky-entity-route" }
infer-decl = { path = "../../infer/husky-infer-decl" }
