[package]
name = "husky-layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
salsa = { path = "../../abstraction/salsa" }
husky-term = { path = "../../kernel/husky-term" }
husky-ty = { path = "../../kernel/husky-ty" }
