[package]
name = "visored-syn-expr"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
either.workspace = true
enum-class.workspace = true
smallvec.workspace = true
thiserror.workspace = true
# abstractions
salsa.workspace = true
idx-arena.workspace = true
# latex
latex-math-letter.workspace = true
latex-prelude.workspace = true
latex-token.workspace = true
latex-ast.workspace = true
# utils
husky-print-utils.workspace = true
husky-tree-utils.workspace = true
# visored
visored-annotation.workspace = true
visored-opr.workspace = true
visored-zfc-ty.workspace = true

[dev-dependencies]
expect-test.workspace = true
# kernel
husky-coword.workspace = true
# latex
latex-command.workspace = true
# visored
visored-syn-expr = { workspace = true, features = ["test_helpers"] }

[lints]
workspace = true

[features]
test_helpers = ["latex-ast/test_helpers"]
