[package]
name = "reserve"
version = "0.0.0"
description = "Reserve for the Husky Programming Language"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]

[dev-dependencies]
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils.workspace = true
