[package]
name = "mayuri-core"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
relative-path.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_yml.workspace = true
walkdir.workspace = true
vec-like.workspace = true
yaml-rust2.workspace = true
# abstractions
idx-arena.workspace = true
# utils
husky-config-utils.workspace = true
husky-sha-utils.workspace = true
husky-make-utils.workspace = true
husky-yaml-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
pathdiff.workspace = true
toml.workspace = true
# utils
husky-path-utils.workspace = true

[lints]
workspace = true
