[package]
name = "__husky"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cyclic-slice = { path = "../../abstraction/cyclic-slice" }
wild-utils = { path = "../../utils/husky-wild-utils" }
husky-vm-interface = { path = "../../vm/husky-vm-interface", features = [
    "any_support",
    "thin_fp",
    "thick_fp",
    "linkage_macro"
] }
husky-datasets-interface = { path = "../domains/ml/husky-datasets-interface", features = [
    "any_support",
] }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }

[lib]
