[package]
name = "salsa"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
arc-swap.workspace = true
crossbeam.workspace = true
crossbeam-utils = { workspace = true, default-features = false }
dashmap.workspace = true
either.workspace = true
hashlink.workspace = true
indexmap.workspace = true
log.workspace = true
parking_lot.workspace = true
relative-path.workspace = true
rustc-hash.workspace = true
stacker.workspace = true
smallvec.workspace = true
# abstractions
salsa-macros.workspace = true
snapshot.workspace = true
enum-index.workspace = true
vec-like.workspace = true
maybe-result.workspace = true
husky-salsa-log-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
test-log = "0.2.11"
env_logger = "*"
rustversion = "1.0"
trybuild = "1.0"
salsa = { path = ".", features = ["test_utils"] }

[features]
test_utils = []
