[package]
name = "husky-completion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
lsp-types = { version = "0.93", features = ["proposed"] }
husky-text = { path = "../../syntax/husky-text" }
husky-ast = { path = "../../syntax/husky-ast" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-opn-syntax = { path = "../../syntax/husky-opn-syntax" }
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
# infer
husky-term-infer = { path = "../../infer/husky-term-infer" }
