[package]
name = "husky-corgi-config"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
semver = "1.0.17"
# abstractions
salsa.workspace = true
# lex
husky-text-protocol.workspace = true
husky-toml-token.workspace = true
# kernel
husky-coword.workspace = true
# fs
husky-fs-specs = { path = "../../fs/husky-fs-specs" }
husky-vfs.workspace = true
# syntax
husky-toml-ast.workspace = true
husky-corgi-config-ast.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]

[features]
test_utils = ["salsa/test_utils"]
