[package]
name = "mnist-classifier"
edition = "2021"
version = "0.1.0"

[dependencies.ad-hoc-task-dependency]
workspace = true

[dependencies.husky-core]
workspace = true

[dependencies.malamute]
workspace = true

[dependencies.mnist]
workspace = true
