[package]
edition = "2021"
name = "husky-token"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "TODO"

[dependencies]
thiserror.workspace = true
ordered-float.workspace = true
paste.workspace = true
serde.workspace = true
serde_json.workspace = true
lsp-types = { workspace = true, features = ["proposed"], optional = true }
# abstractions
parsec.workspace = true
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
shifted-unsigned-int.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text-protocol.workspace = true
husky-token-data.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-term-prelude.workspace = true
# syntax
husky-opr.workspace = true
# utils
husky-expect-test-snippets-utils = { path = "../../utils/husky-expect-test-snippets-utils" }
husky-wild-utils.workspace = true
husky-check-utils.workspace = true
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[lib]

[dev-dependencies]
expect-test.workspace = true
indicatif = "0.17.2"
# fs
husky-vfs = { workspace = true, features = ["test_utils"] }
# kernel
husky-entity-path.workspace = true
# utils
husky-adversarial-utils = { path = "../../utils/husky-adversarial-utils" }
husky-token = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["husky-vfs/test_utils"]
