[package]
name = "husky-vfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = "1.0.37"
notify-debouncer-mini = "0.2.0"
salsa = { path = "../../abstraction/salsa" }
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
eyre = "0.6.8"
replace_with = "0.1.7"
# abstraction
place = { path = "../../abstraction/place" }
# fs
husky-source-path = { path = "../../fs/husky-source-path" }
husky-absolute-path = { path = "../../fs/husky-absolute-path" }
# lex
husky-text = { path = "../../lex/husky-text" }
# kernel
husky-package-path = { path = "../../kernel/husky-package-path" }
husky-entity-path = { path = "../../kernel/husky-entity-path" }
# utils
husky-print-utils = { path = "../../utils/husky-print-utils" }

[dev-dependencies]
tempfile = "3.3.0"
husky-toolchain = { path = "../../kernel/husky-toolchain" }
husky-word = { path = "../../kernel/husky-word" }
