[package]
name = "visored-lean-transpilation"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
convert_case.workspace = true
either.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
# abstractions
interned.workspace = true
salsa = { workspace = true, optional = true }
# latex
latex-prelude.workspace = true
# lean
lean-coword.workspace = true
lean-mir-expr.workspace = true
lean-entity-path.workspace = true
lean-opr.workspace = true
lean-term.workspace = true
# utils
husky-print-utils.workspace = true
husky-tree-utils.workspace = true
# visored
visored-annotation.workspace = true
visored-entity-path.workspace = true
visored-mir-expr.workspace = true
visored-opr.workspace = true
visored-prelude.workspace = true
visored-term.workspace = true

[dev-dependencies]
expect-test.workspace = true
# kernel
husky-coword.workspace = true
# latex
latex-command.workspace = true
latex-environment.workspace = true
latex-ast.workspace = true
latex-token.workspace = true
# lean
lean-term.workspace = true
lean-sem-expr.workspace = true
# utils
husky-path-utils.workspace = true
# visored
visored-sem-expr.workspace = true
visored-syn-expr.workspace = true
visored-global-dispatch.workspace = true
visored-signature.workspace = true
visored-annotation.workspace = true
latex-vfs.workspace = true

[lints]
workspace = true
