[package]
name = "husky-absolute-path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = "1.0.37"
# abstraction
salsa = { path = "../../abstraction/salsa" }
# kernel
husky-entity-path = { path = "../../kernel/husky-entity-path" }
husky-package-path = { path = "../../kernel/husky-package-path" }
