[package]
name = "husky-syn-defn"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# infer
husky-manifest.workspace = true
# kernel
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-coword.workspace = true
# lex
husky-token.workspace = true
# syntax
husky-text.workspace = true
husky-ast.workspace = true
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# abstractions
salsa = { path = "../../abstractions/salsa", features = ["test_helpers"] }
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
# infer
husky-corgi-config.workspace = true
# kernel
husky-term-prelude.workspace = true
# lex
husky-toml-token.workspace = true
husky-token-data.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-defn = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
