[package]
name = "husky-ide-fmt"
version.workspace = true
edition = "2021"

[dependencies]
salsa.workspace = true

[dev-dependencies]
husky-ide-fmt = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
