[package]
name = "husky-linket-impl"
version.workspace = true
edition = "2021"

[dependencies]
serde.workspace = true
smallvec.workspace = true
vec-like.workspace = true
# abstractions
# kernel
husky-item-path-interface.workspace = true
# ki
husky-ki-repr-interface.workspace = true
# protocols
husky-value-protocol.workspace = true
# value
husky-value.workspace = true
# utils
husky-decl-macro-utils.workspace = true
husky-wild-utils.workspace = true

[dev-dependencies]
# library
husky-core.workspace = true

[features]
ugly = [
    "husky-item-path-interface/ugly",
    "husky-value-protocol/ugly",
    "husky-value/ugly"
]
