[package]
name = "husky-mizar"
version = "0.1.0"
authors = ["Mario Carneiro <di.gama@gmail.com>"]
edition = "2021"
description = "Mizar verifier toolchain"
repository = "https://github.com/digama0/mizar-rs"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["theorem", "proving", "proof", "verifier"]
categories = ["command-line-utilities", "development-tools", "mathematics"]

[dependencies]
quick-xml = "0.28.1"
once_cell = "1.12"
enum-map = "2.4"
backtrace = "0.3"
itertools = "0.10"
paste = "1.0"
ctrlc = "3.2"
pretty = "0.11"
num-bigint = "0.4"
num-traits = "0.2"
stacker = "0.1"
memchr = "2.5"
radix_trie = "0.2"
im = "15.1"
bytecount = "0.6.3"
indicatif = "0.17.3"
clap = { version = "4.1.10", features = ["derive"] }
num_cpus = "1.15"
# abstractions
idx.workspace = true
