[package]
edition = "2021"
name = "husky-text"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
rustc-hash = "1.1.0"
lsp-types = { version = "0.93", features = ["proposed"], optional = true }
serde = { version = "1.0.106", features = ["derive"] }
# kernel
husky-word = { path = "../../kernel/husky-word" }
# utils
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }

[features]
lsp_support = ["dep:lsp-types"]
