[package]
name = "husky-ml-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dashmap.workspace = true
either.workspace = true
serde.workspace = true
# abstractions
salsa.workspace = true
# comptime
husky-rust-transpilation.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-standard-value.workspace = true
# linkage
husky-linkage.workspace = true
husky-linkage-impl.workspace = true
# linktime
husky-mono-linktime.workspace = true
# protocols
husky-trace-protocol.workspace = true
husky-visual-protocol.workspace = true
# tasks
husky-task-interface.workspace = true
husky-task.workspace = true
husky-ml-task-interface.workspace = true
# val
husky-val.workspace = true
