[package]
name = "husky-models-static-defn"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = { version = "1.0.48", features = ["preserve_order"] }
ordered-float = "3.0.0"
husky-word = { path = "../../../../syntax/husky-word" }
husky-entity-route = { path = "../../../../syntax/husky-entity-route" }
husky-vm = { path = "../../../../vm/husky-vm" }
husky-print-utils = { path = "../../../../utils/husky-print-utils" }
husky-dev-utils = { path = "../../../../utils/husky-dev-utils" }
husky-static-visualizer = { path = "../../../../static/husky-static-visualizer" }
husky-entity-kind = { path = "../../../../syntax/husky-entity-kind" }
husky-static-defn = { path = "../../../husky-static-defn" }
husky-liason-semantics = { path = "../../../../semantics/husky-liason-semantics" }
husky-trace-protocol = { path = "../../../../tracetime/husky-trace-protocol" }
husky-vm-register-method = { path = "../../../../vm/husky-vm-register-method" }

[build-dependencies]
husky-rust-code-repr = { path = "../../../../comptime/husky-rust-code-repr" }
husky-write-utils = { path = "../../../../utils/husky-write-utils" }
husky-io-utils = { path = "../../../../utils/husky-io-utils" }
