[package]
name = "husky-vmir"
version.workspace = true
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56"

[lib]
doctest = false

[dependencies]
either.workspace = true
smallvec.workspace = true
# abstractions
idx-arena.workspace = true
enum-class.workspace = true
salsa.workspace = true
shifted-unsigned-int.workspace = true
version-stamp.workspace = true
# hir
husky-hir-opr.workspace = true
husky-hir-eager-expr.workspace = true
husky-hir-expr.workspace = true
husky-hir-decl.workspace = true
husky-hir-defn.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-expr.workspace = true
husky-hir-ty.workspace = true
husky-place.workspace = true
husky-standard-value = { workspace = true, features = ["constant"] }
# ki
husky-ki.workspace = true
husky-ki-repr.workspace = true
# linket
husky-linket.workspace = true
husky-linket-impl.workspace = true
husky-virtual-linket-impl.workspace = true
# linktime
husky-linktime.workspace = true
husky-virtual-linktime.workspace = true
# syntax
husky-entity-kind.workspace = true
husky-ast.workspace = true
husky-opr.workspace = true
# devsoul
# husky-devsoul-interface.workspace = true
husky-devsoul.workspace = true
# utils
husky-check-utils.workspace = true
husky-control-flow-utils.workspace = true
husky-lifetime-utils.workspace = true
husky-print-utils.workspace = true
# value
husky-value.workspace = true
husky-literal-value.workspace = true

[dev-dependencies]
# fs
husky-manifest.workspace = true
husky-vfs.workspace = true
# hir
husky-hir-ty.workspace = true
husky-hir-eager-expr.workspace = true
husky-hir-lazy-expr.workspace = true
husky-hir-expr.workspace = true
husky-hir-prelude.workspace = true
# kernel
husky-eth-signature.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-dec-signature.workspace = true
husky-eth-term.workspace = true
husky-fly-term.workspace = true
# ki
husky-ki.workspace = true
husky-ki-repr.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-toml-token.workspace = true
# linket
husky-javelin.workspace = true
husky-linket.workspace = true
# semantics
husky-corgi-config.workspace = true
husky-sem-expr.workspace = true
husky-sem-place-contract.workspace = true
husky-sem-item-path-deps.workspace = true
husky-sem-static-mut-deps.workspace = true
husky-sem-var-deps.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-decl.workspace = true
husky-corgi-config-ast.workspace = true
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-defn.workspace = true

[features]
