[package]
name = "husky-platform"
version = "0.1.0"
edition = "2021"
description = "representation of a target platform for the Husky programming language"
homepage = "https://github.com/xiyuzhai-husky-lang/husky"
keywords = ["husky", "platform"]
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde.workspace = true
