[package]
name = "quick-sort-linkages"
edition = "2021"
version = "0.1.0"

[dependencies.husky-core]
workspace = true

[dependencies.quick-sort]
workspace = true

[lib]
plugin = false
proc-macro = false
required-features = []
crate-type = ["cdylib"]
