[package]
name = "husky-coword"
version.workspace = true
edition = "2021"

[dependencies]
expect-test.workspace = true
once_cell = "1.16.0"
# abstractions
salsa.workspace = true
vec-like.workspace = true
# utils
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
husky-coword = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
