[package]
name = "husky-manifest-ast"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
# lex
husky-text-protocol.workspace = true
husky-toml-token.workspace = true
# kernel
husky-coword.workspace = true
# fs
husky-vfs.workspace = true
# syntax
husky-toml-ast.workspace = true

[dev-dependencies]
husky-manifest-ast = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
