[package]
name = "husky-data-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = { version = "1.0.48", features = ["preserve_order"] }
salsa = "0.17.0-pre.2"
husky-comptime = { path = "../../comptime/husky-comptime" }
husky-vm-interface = { path = "../../vm/husky-vm-interface" }
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
husky-entity-route = { path = "../../concept/husky-entity-route" }
husky-vm-binding = { path = "../../vm/husky-vm-binding" }
husky-word = { path = "../../concept/husky-word" }
