[package]
name = "cybertron-mini-lean-compiler-linkets"
edition = "2021"
version = "0.1.0"

[dependencies.ad-hoc-devsoul-dependency]
workspace = true

[dependencies.cybertron-mini-lean-compiler]
workspace = true

[dependencies.husky-core]
workspace = true

[lib]
plugin = false
proc-macro = false
required-features = []
crate-type = ["cdylib"]
