[package]
name = "husky-rust-transpilation"
version.workspace = true
edition = "2021"

[dependencies]
toml.workspace = true
cargo-manifest.workspace = true
pathdiff.workspace = true
relative-path.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
either.workspace = true
enum-class.workspace = true
vec-like.workspace = true
is.workspace = true
# fs
husky-vfs.workspace = true
# hir
husky-hir-ty.workspace = true
husky-hir-eager-expr.workspace = true
husky-hir-lazy-expr.workspace = true
husky-hir-expr.workspace = true
husky-hir-decl.workspace = true
husky-hir-defn.workspace = true
husky-hir-opr.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-eth-signature.workspace = true
husky-devsoul.workspace = true
husky-term-prelude.workspace = true
husky-place.workspace = true
husky-opr.workspace = true
husky-expr.workspace = true
# lex
# linket
husky-javelin.workspace = true
husky-linket.workspace = true
# semantics
husky-manifest.workspace = true
husky-corgi-config.workspace = true
husky-sem-var-deps.workspace = true
# syntax
husky-entity-tree.workspace = true
# devsoul
husky-devsoul-interface.workspace = true
# utils
husky-fmt-utils.workspace = true
husky-io-utils.workspace = true
husky-print-utils.workspace = true

[dev-dependencies]
# hir
husky-hir-prelude.workspace = true
# kernel
husky-eth-term.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-dec-signature.workspace = true
husky-fly-term.workspace = true
husky-place.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-toml-token.workspace = true
# linket
husky-javelin.workspace = true
# semantics
husky-manifest.workspace = true
husky-corgi-config.workspace = true
husky-sem-expr.workspace = true
husky-sem-place-contract.workspace = true
husky-sem-item-path-deps.workspace = true
husky-sem-static-mut-deps.workspace = true
husky-sem-var-deps.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-entity-tree.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true

[features]
test_utils = ["salsa/test_utils"]
