[package]
name = "husky-token-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror.workspace = true
ordered-float.workspace = true
paste.workspace = true
expect-test = "1.4.0"
serde.workspace = true
serde_json.workspace = true
lsp-types = { version = "=0.94", features = ["proposed"], optional = true }
# abstractions
parsec.workspace = true
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text-protocol.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-term-prelude.workspace = true
husky-opr.workspace = true
# protocols
husky-token-protocol = { path = "../../protocols/husky-token-protocol", optional = true }
# syntax
husky-syn-opr.workspace = true
# utils
husky-expect-test-snippets-utils = { path = "../../utils/husky-expect-test-snippets-utils" }
wild-utils = { path = "../../utils/husky-wild-utils" }
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
husky-token-data = { path = ".", features = ["test_utils"] }

[features]
protocol_support = ["dep:husky-token-protocol"]
test_utils = ["salsa/test_utils"]
