[package]
name = "husky-token-data"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
ordered-float.workspace = true
paste.workspace = true
serde.workspace = true
serde_json.workspace = true
lsp-types = { workspace = true, optional = true }
# abstractions
parsec.workspace = true
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text-protocol.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-term-prelude.workspace = true
husky-opr.workspace = true
# protocols
husky-token-protocol = { workspace = true, optional = true }
# syntax
husky-syn-opr.workspace = true
# utils
husky-expect-test-snippets-utils = { path = "../../utils/husky-expect-test-snippets-utils" }
husky-wild-utils.workspace = true
husky-check-utils.workspace = true
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
expect-test.workspace = true
husky-token-data = { path = ".", features = ["test_utils"] }

[features]
protocol_support = ["dep:husky-token-protocol"]
test_utils = ["salsa/test_utils"]
