# Add the contents of this file to `config.toml` to enable "fast build" configuration. Please read the notes below.
# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.
[target.x86_64-unknown-linux-gnu]
linker = "clang"
# rustflags = ["-Awarnings", "-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]
# following instructions on https://github.com/rui314/mold to install mold
# use g++-10 instead of c++ in the cmake flag
rustflags = ["-Awarnings", "-Clink-arg=-fuse-ld=mold", "-Zshare-generics=y"]

# NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# `brew install michaeleisel/zld/zld`
[target.x86_64-apple-darwin]
rustflags = [
    "-Awarnings",
    # "-C",
    # "link-arg=-fuse-ld=/usr/local/bin/zld",
    "-Zshare-generics=y"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Awarnings",
    # "-C",
    # "link-arg=-fuse-ld=/opt/homebrew/bin/zld",
    "-Zshare-generics=y"
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Awarnings", "-Zshare-generics=n"]

# Optional: Uncommenting the following improves compile times, but reduces the amount of debug info to 'line number tables only'
# In most cases the gains are negligible, but if you are on macos and have slow compile times you should see significant gains.
[profile.dev]
debug = 1
