[package]
name = "husky-dec-term"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
ordered-float.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
# syntax
husky-entity-tree.workspace = true
# utils
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
# kernel
husky-coword.workspace = true
# lex
husky-token.workspace = true

[features]
test_utils = ["salsa/test_utils"]
