[package]
name = "cargo-organise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
regex = "1"
toml = "0.5.9"
toml_edit = "0.15.0"
cargo-udeps = { git = "https://github.com/husky-lang-org/cargo-udeps" }
