[package]
edition = "2021"
name = "husky-atom"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
salsa = "0.17.0-pre.2"
# abstraction
fold = { path = "../../abstraction/fold" }
vec-like = { path = "../../abstraction/vec-like" }
map-collect = { path = "../../abstraction/map-collect" }
# forks
thin-vec = { path = "../../../forks/thin-vec" }
# kernel
husky-word = { path = "../../kernel/husky-word" }
husky-entity-route = { path = "../../kernel/husky-entity-route" }
# semantics
husky-liason-semantics = { path = "../../semantics/husky-liason-semantics" }
# static
husky-static-defn = { path = "../../static/husky-static-defn" }
# syntax
husky-file = { path = "../../syntax/husky-file" }
husky-text = { path = "../../syntax/husky-text" }
husky-token = { path = "../../syntax/husky-token" }
husky-entity-syntax = { path = "../../syntax/husky-entity-syntax" }
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
husky-defn-head = { path = "../../syntax/husky-defn-head" }
husky-primitive-literal-syntax = { path = "../../syntax/husky-primitive-literal-syntax" }
husky-pattern-syntax = { path = "../../syntax/husky-pattern-syntax" }
husky-opn-syntax = { path = "../../syntax/husky-opn-syntax" }
# utils
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }
interner = { path = "../../abstraction/interner" }
