[package]
name = "latex-token"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
# abstractions
enum-class.workspace = true
salsa.workspace = true
shifted-unsigned-int.workspace = true
# kernel
husky-coword.workspace = true
# protocols
husky-text-protocol.workspace = true
# tex
latex-command.workspace = true
latex-math-letter.workspace = true
latex-math-opr.workspace = true
latex-prelude.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true

[lints]
workspace = true
