[package]
name = "husky-token-info"
version.workspace = true
edition = "2021"

[dependencies]
smallvec.workspace = true
# abstractions
enum-class.workspace = true
salsa.workspace = true
# fs
husky-vfs.workspace = true
# infer
husky-sem-expr.workspace = true
# kernel
husky-entity-kind = { path = "../../kernel/husky-entity-kind", features = [
    "protocol_support"
] }
husky-entity-path.workspace = true
husky-place.workspace = true
# lex
husky-token-data = { path = "../../lex/husky-token-data", features = [
    "protocol_support"
] }
husky-token.workspace = true
husky-regional-token.workspace = true
husky-text-protocol.workspace = true
# protocols
husky-entity-protocol = { workspace = true, optional = true }
husky-token-protocol = { path = "../../protocols/husky-token-protocol", optional = true }
# semantics
husky-sem-opr = { path = "../../semantics/husky-sem-opr" }
# syntax
husky-ast.workspace = true
husky-item-decl-ast.workspace = true
husky-item-defn-ast.workspace = true
husky-entity-tree.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
husky-print-utils.workspace = true

[dev-dependencies]
# fs
husky-manifest.workspace = true
husky-corgi-config.workspace = true
husky-vfs = { workspace = true, features = ["test_helpers"] }
# kernel
husky-coword.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-dec-signature.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
# semantics
husky-sem-place-contract.workspace = true
# lex
husky-text.workspace = true
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true
husky-token-info = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
protocol_support = ["dep:husky-entity-protocol", "dep:husky-token-protocol"]
