[package]
name = "husky-fs-specs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror.workspace = true
dirs = "4.0.0"
husky-path-utils = { path = "../../utils/husky-path-utils" }
