[package]
name = "husky-ethereal-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
either.workspace = true
once_cell = "1.16.0"
optional = "0.5.0"
thiserror.workspace = true
ordered-float.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
maybe-result = { path = "../../abstractions/maybe-result" }
# fs
husky-vfs.workspace = true
# infer
husky-declarative-signature.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-declarative-term.workspace = true
husky-declarative-ty.workspace = true
husky-scope = { path = "../../kernel/husky-scope" }
# lex
husky-token-data.workspace = true
# syntax
husky-entity-syn-tree.workspace = true
husky-syn-decl.workspace = true
# utils
husky-print-utils.workspace = true
husky-unicode-symbols.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_utils"] }
# kernel
husky-coword.workspace = true
# infer
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# lex
husky-token.workspace = true
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-expr.workspace = true
husky-corgi-config-ast.workspace = true
husky-ethereal-term = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
