[package]
name = "visored-signature"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
rustc-hash.workspace = true
salsa.workspace = true
# abstractions
enum-class.workspace = true
# lisp
lisp-csv.workspace = true
# visored
visored-term.workspace = true

[dev-dependencies]
expect-test.workspace = true
# kernel
husky-coword.workspace = true
# latex
latex-vfs.workspace = true
# utils
husky-path-utils.workspace = true
# visored
visored-entity-path.workspace = true

[lints]
workspace = true
