[package]
name = "visored-pipeline"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
rayon.workspace = true
relative-path = { workspace = true, features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml.workspace = true
thiserror.workspace = true
tokio.workspace = true
# abstractions
alien-seed.workspace = true
eterned.workspace = true
idx-arena.workspace = true
# latex
latex-prelude.workspace = true
latex-vfs.workspace = true
# lean
lean-helpers.workspace = true
lean-mir-expr.workspace = true
# llms
all-llms.workspace = true
llm-prelude.workspace = true
# utils
husky-io-utils.workspace = true
husky-print-utils.workspace = true
# visored
visored-lean-transpilation.workspace = true
visored-mir-expr.workspace = true
visored-models.workspace = true
visored-syn-expr.workspace = true

[dev-dependencies]
expect-test.workspace = true
tempfile.workspace = true
# utils
husky-path-utils.workspace = true

[lints]
workspace = true
