[package]
name = "husky-datasets-protocol"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version = "1.0.106", features = ["derive"], optional = true }
husky-signal = { path = "../../../../abstractions/husky-signal", optional = true }

[features]
serde_support = ["dep:serde"]
signal_support = ["dep:husky-signal"]
