[package]
name = "husky-static-visualizer"
version = "0.0.0"
edition = "2021"

[dependencies]
husky-vm-interface = { path = "../../vm/husky-vm-interface" }
husky-trace-protocol = { path = "../../Devtime/husky-trace-protocol" }
