[package]
name = "husky-diagnostics"
version = "0.0.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
lsp-types.workspace = true
# abstractions
salsa.workspace = true
# fs
husky-vfs.workspace = true
# infer
husky-sem-expr.workspace = true
# kernel
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-entity-kind.workspace = true
husky-fly-term.workspace = true
husky-place.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-regional-token.workspace = true
# syntax
husky-text-protocol = { path = "../../protocols/husky-text-protocol", features = [
    "lsp_support"
] }
husky-entity-tree.workspace = true
husky-scope-expr.workspace = true
husky-ast.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
# utils
husky-check-utils.workspace = true
husky-print-utils.workspace = true

[dev-dependencies]
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
# lex
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-syn-expr.workspace = true
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true
# infer
husky-manifest.workspace = true
husky-dec-signature.workspace = true
husky-corgi-config.workspace = true
# utils
husky-path-utils.workspace = true
husky-diagnostics = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
