[package]
name = "husky-opr"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# abstractions
enum-class.workspace = true
# lex
husky-text-protocol.workspace = true
# kernel
husky-coword.workspace = true
# utils
husky-print-utils.workspace = true
husky-check-utils = { path = "../../utils/husky-check-utils" }
