[package]
name = "husky-term-prelude"
version.workspace = true
edition = "2021"

[dependencies]
ordered-float.workspace = true
thiserror.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
# utils
husky-print-utils.workspace = true
# value
husky-literal-value.workspace = true

[dev-dependencies]
husky-term-prelude = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
