[package]
name = "husky-hover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
lsp-types = { version = "0.93", features = ["proposed"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = { version = "1.0.48", features = ["preserve_order"] }
# utils
husky-print-utils = { path = "../../utils/husky-print-utils" }
# kernel
husky-entity-route = { path = "../../kernel/husky-entity-route" }
husky-text = { path = "../../syntax/husky-text" }
# syntax
husky-ast = { path = "../../syntax/husky-ast" }
husky-file = { path = "../../syntax/husky-file" }
husky-expr-syntax = { path = "../../syntax/husky-expr-syntax" }
# infer
husky-term-infer = { path = "../../infer/husky-term-infer" }
# ide
husky-documentation = { path = "../../ide/husky-documentation" }
