[package]
name = "husky-hover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
# abstractions
salsa.workspace = true
# fs
husky-vfs.workspace = true
# ide
husky-documentation = { path = "../../ide/husky-documentation" }
# infer
husky-token-info.workspace = true
# lex
husky-token-data.workspace = true
husky-token.workspace = true
husky-text-protocol.workspace = true
# kernel
husky-ethereal-term.workspace = true
husky-ethereal-signature.workspace = true
# syntax
husky-ast.workspace = true
husky-syn-expr.workspace = true
husky-entity-syn-tree.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_utils"] }
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-declarative-term.workspace = true
husky-declarative-ty.workspace = true
husky-ethereal-term.workspace = true
husky-ethereal-signature.workspace = true
husky-fluffy-term.workspace = true
# lex
husky-text = { path = "../../lex/husky-text", features = ["lsp_support"] }
husky-toml-token.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
husky-corgi-config-ast.workspace = true
# infer
husky-manifest.workspace = true
husky-declarative-signature.workspace = true
husky-sema-expr.workspace = true
husky-corgi-config.workspace = true
husky-hover = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
