[package]
name = "husky-task-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
once_cell.workspace = true
smallvec.workspace = true
serde.workspace = true
# abstractions
shifted-unsigned-int.workspace = true
serde-impl.workspace = true
# protocols
husky-value-protocol.workspace = true
# tasks
husky-task-interface-macros.workspace = true
# utils
husky-decl-macro-utils.workspace = true
