[package]
name = "husky-trace"
version = "0.0.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
# devtime
# fs
husky-vfs.workspace = true
# hir
husky-hir-eager-expr.workspace = true
husky-hir-lazy-expr.workspace = true
husky-hir-expr.workspace = true
husky-hir-decl.workspace = true
husky-hir-defn.workspace = true
# ide
husky-token-info = { workspace = true, features = ["protocol_support"] }
# kernel
husky-entity-path.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-coword.workspace = true
husky-entity-kind.workspace = true
# lex
husky-text.workspace = true
husky-token.workspace = true
husky-regional-token.workspace = true
# protocols
husky-text-protocol.workspace = true
husky-trace-protocol.workspace = true
# ki
husky-ki-repr.workspace = true
# syntax
husky-ast.workspace = true
husky-syn-expr.workspace = true
husky-syn-decl.workspace = true
husky-syn-defn.workspace = true
husky-entity-tree.workspace = true
# semantics
husky-manifest.workspace = true
husky-sem-expr.workspace = true
# utils
husky-check-utils.workspace = true
husky-print-utils.workspace = true

[dev-dependencies]
# hir
husky-hir-ty.workspace = true
husky-hir-opr.workspace = true
# kernel
husky-coword.workspace = true
husky-term-prelude.workspace = true
husky-eth-signature.workspace = true
husky-eth-term.workspace = true
husky-dec-term.workspace = true
husky-dec-ty.workspace = true
husky-dec-signature.workspace = true
husky-fly-term.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
husky-toml-token.workspace = true
# linkage
husky-javelin.workspace = true
husky-linkage.workspace = true
# semantics
husky-corgi-config.workspace = true
husky-sem-expr.workspace = true
husky-sem-place-contract.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-entity-tree = { path = "../../syntax/husky-entity-tree", features = [
    "test_utils"
] }
husky-syn-decl = { path = "../../syntax/husky-syn-decl", features = [
    "test_utils"
] }
husky-syn-expr = { path = "../../syntax/husky-syn-expr", features = [
    "test_utils"
] }
husky-syn-defn = { path = "../../syntax/husky-syn-defn", features = [
    "test_utils"
] }
# toml
husky-corgi-config-ast.workspace = true
husky-manifest-ast.workspace = true
husky-toml-ast.workspace = true
# ki
husky-ki = { path = "../../ki/husky-ki", features = ["test_utils"] }
husky-ki-repr = { path = "../../ki/husky-ki-repr", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
