[package]
name = "husky-hir-ty"
version.workspace = true
edition = "2021"

[dependencies]
either.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
vec-like.workspace = true
enum-class.workspace = true
maybe-result.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-entity-path.workspace = true
husky-term-prelude.workspace = true
husky-eth-term.workspace = true
husky-eth-signature.workspace = true
husky-fly-term.workspace = true
husky-scope.workspace = true
husky-place = { path = "../../kernel/husky-place" }
husky-hir-prelude = { path = "../../hir/husky-hir-prelude" }
# semantics
husky-sem-place-contract.workspace = true
husky-sem-var-deps.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
husky-hir-ty = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
