[package]
name = "husky-scope"
version.workspace = true
edition = "2021"

[dependencies]
# abstractions
salsa.workspace = true
with-db.workspace = true
enum-class.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-token.workspace = true

[dev-dependencies]
# kernel
husky-coword.workspace = true
husky-vfs = { workspace = true, features = ["test_utils"] }
