[package]
name = "husky-trace-protocol"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.86"
log = "0.4.6"
smallvec = { version = "1.9.0", features = ["serde"] }
# abstraction
vec-like = { path = "../../abstraction/vec-like" }
husky-signal = { path = "../../abstraction/husky-signal" }
ref-arena = { path = "../../abstraction/ref-arena" }
trackable = { path = "../../abstraction/trackable" }
# vm
husky-vm-primitive-value = { path = "../../vm/husky-vm-primitive-value", features = [
    "serde_support"
] }
# runtime
husky-feature-protocol = { path = "../../runtime/husky-feature-protocol" }

[dependencies.web-sys]
version = "0.3.57"
features = ['ImageData']
