[package]
name = "husky-toml-ast"
version.workspace = true
edition = "2021"

[dependencies]
toml_datetime = "0.6.1"
thiserror.workspace = true
ordered-float.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
idx-arena.workspace = true
vec-like.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-coword.workspace = true
# lex
husky-toml-token.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
# fs
husky-vfs = { workspace = true, features = ["test_helpers"] }
husky-toml-ast = { path = ".", features = ["test_helpers"] }

[features]
test_helpers = ["salsa/test_helpers"]
