[package]
name = "latex-command"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
rustc-hash.workspace = true
thiserror.workspace = true
# abstractions
coword.workspace = true
salsa = { workspace = true, optional = true }
# kernel
husky-coword.workspace = true
# latex
latex-prelude.workspace = true
latex-math-letter.workspace = true
# lisp
lisp-csv.workspace = true

[dev-dependencies]
husky-path-utils.workspace = true
# latex
latex-command.workspace = true

[lints]
workspace = true
