[package]
name = "husky-syn-decl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror.workspace = true
derive-getters = "0.2.0"
either.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
vec-like.workspace = true
original-error.workspace = true
parsec.workspace = true
# fs
husky-vfs.workspace = true
# kernel
husky-entity-path.workspace = true
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-opr.workspace = true
# lex
husky-token-data.workspace = true
husky-regional-token.workspace = true
# syntax
husky-syn-expr.workspace = true
husky-entity-syn-tree.workspace = true
husky-decl-ast = { path = "../../syntax/husky-decl-ast" }
# utils
husky-print-utils.workspace = true

[dev-dependencies]
# fs
husky-vfs = { workspace = true, features = ["test_utils"] }
# kernel
husky-term-prelude.workspace = true
# lex
husky-toml-token.workspace = true
husky-token = { path = "../../lex/husky-token", features = ["test_utils"] }
# semantics
husky-manifest.workspace = true
husky-corgi-config.workspace = true
# syntax
husky-ast = { workspace = true, features = ["test_utils"] }
husky-toml-ast.workspace = true
husky-manifest-ast.workspace = true
husky-corgi-config-ast.workspace = true
husky-syn-decl = { path = ".", features = ["test_utils"] }

[features]
test_utils = ["salsa/test_utils"]
