[package]
name = "lean-mir-expr"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
lazy_static.workspace = true
# abstractions
idx-arena.workspace = true
smallvec.workspace = true
salsa = { workspace = true, optional = true }
# lean
lean-coword.workspace = true
lean-entity-path.workspace = true
lean-opr.workspace = true
lean-term.workspace = true
# utils
husky-tree-utils.workspace = true

[lints]
workspace = true
