[package]
name = "husky-standard-trace-protocol"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
egui = { workspace = true, optional = true }
rustc-hash.workspace = true
serde.workspace = true
# abstractions
enum-class.workspace = true
vec-like.workspace = true
ui.workspace = true
# kernel
husky-item-path-interface.workspace = true
# ki
husky-ki-repr-interface.workspace = true
# linket
husky-linket-impl.workspace = true
husky-standard-linket-impl.workspace = true
# protocols
husky-visual-protocol.workspace = true
husky-trace-protocol.workspace = true
husky-standard-devsoul-interface.workspace = true
# utils
husky-control-flow-utils.workspace = true

[lints]
workspace = true

[features]
egui = ["dep:egui"]
