[package]
name = "husky-toolchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
expect-test = "1.4.0"
once_cell = "1.16.0"
# abstraction
salsa = { path = "../../abstraction/salsa" }
# platform
husky-platform = { path = "../../kernel/husky-platform" }
# utils
husky-path-utils = { path = "../../utils/husky-path-utils" }
