[package]
edition = "2021"
name = "husky-defn-head"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
salsa = "0.17.0-pre.2"
thin-vec = { path = "../../../forks/thin-vec" }
# abstraction
interner = { path = "../../abstraction/interner" }
upcast = { path = "../../abstraction/upcast" }
vec-like = { path = "../../abstraction/vec-like" }
fold = { path = "../../abstraction/fold" }
# syntax
husky-file = { path = "../../syntax/husky-file" }
husky-text = { path = "../../syntax/husky-text" }
husky-token = { path = "../../syntax/husky-token" }
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
husky-entity-syntax = { path = "../../syntax/husky-entity-syntax" }
# kernel
husky-word = { path = "../../kernel/husky-word" }
husky-entity-route = { path = "../../kernel/husky-entity-route" }
# static
husky-static-defn = { path = "../../static/husky-static-defn" }
# semantics
husky-liason-semantics = { path = "../../semantics/husky-liason-semantics" }
# utils
husky-path-utils = { path = "../../utils/husky-path-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-check-utils = { path = "../../utils/husky-check-utils" }
