[package]
edition = "2021"
name = "husky-defn-head"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
salsa = { path = "../../abstraction/salsa" }
thin-vec = { path = "../../../forks/thin-vec" }
# abstraction
upcast = { path = "../../abstraction/upcast" }
vec-like = { path = "../../abstraction/vec-like" }
# lex
husky-text = { path = "../../lex/husky-text" }
husky-token = { path = "../../lex/husky-token" }
# kernel
husky-word = { path = "../../kernel/husky-word" }
husky-term = { path = "../../kernel/husky-term" }
husky-absolute-path = { path = "../../kernel/husky-absolute-path" }
# syntax
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
husky-entity-tree = { path = "../../syntax/husky-entity-tree" }
# utils
husky-path-utils = { path = "../../utils/husky-path-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
husky-check-utils = { path = "../../utils/husky-check-utils" }
