[package]
edition = "2021"
name = "husky-entity-tree"
version.workspace = true
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "TODO"

[dependencies]
thiserror.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
with-db.workspace = true
is.workspace = true
idx-arena.workspace = true
vec-like.workspace = true
original-error.workspace = true
parsec.workspace = true
maybe-result.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
# todo: make this optional and add feature tokra
husky-regional-token.workspace = true
# kernel
husky-coword.workspace = true
husky-entity-path.workspace = true
husky-entity-kind.workspace = true
husky-scope.workspace = true
# protocols
husky-text-protocol.workspace = true
# syntax
husky-ast.workspace = true
husky-opr.workspace = true
husky-scope-expr.workspace = true
husky-crate-decl-ast.workspace = true
husky-item-decl-ast.workspace = true
husky-item-defn-ast.workspace = true
# infer
husky-manifest.workspace = true
# utils
husky-path-utils.workspace = true
husky-print-utils.workspace = true
husky-check-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
# fs
husky-corgi-config.workspace = true
husky-vfs = { workspace = true, features = ["test_helpers"] }
# kernel
husky-term-prelude = { path = "../../kernel/husky-term-prelude", features = [
    "test_helpers"
] }
# syntax
husky-ast = { workspace = true, features = ["test_helpers"] }
husky-entity-tree = { path = ".", features = ["test_helpers"] }
# toml
husky-corgi-config-ast.workspace = true
husky-manifest-ast.workspace = true
husky-toml-ast.workspace = true
husky-toml-token.workspace = true

[features]
test_helpers = ["salsa/test_helpers"]
