[package]
edition = "2021"
name = "husky-ast"
version.workspace = true
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "TODO"

[dependencies]
lsp-types.workspace = true
either.workspace = true
ordered-float.workspace = true
thiserror.workspace = true
smallvec.workspace = true
# abstractions
salsa.workspace = true
enum-class.workspace = true
vec-like.workspace = true
idx-arena.workspace = true
original-error.workspace = true
parsec.workspace = true
# fs
husky-vfs.workspace = true
# lex
husky-text.workspace = true
husky-token-data.workspace = true
husky-token.workspace = true
# kernel
husky-entity-path.workspace = true
husky-coword.workspace = true
husky-entity-kind.workspace = true
husky-scope.workspace = true
# syntax
husky-opr.workspace = true
husky-scope-expr.workspace = true
# utils
husky-print-utils.workspace = true

[dev-dependencies]
expect-test.workspace = true
# fs
husky-vfs = { workspace = true, features = ["test_utils"] }
# kernel
husky-term-prelude.workspace = true
# lex
husky-token = { path = "../../lex/husky-token", features = ["test_utils"] }
# syntax
husky-ast = { path = ".", features = ["test_utils"] }
# utils
husky-path-utils.workspace = true

[features]
test_utils = ["husky-vfs/test_utils", "husky-token/test_utils"]
