[package]
edition = "2021"
name = "husky-ast"
version = "0.0.0"
authors = ["Xiyu Zhai"]
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[dependencies]
lsp-types = { version = "0.93", features = ["proposed"] }
ordered-float = "3.0.0"
salsa = "0.17.0-pre.2"
# forks
thin-vec = { path = "../../../forks/thin-vec" }
# utils
husky-check-utils = { path = "../../utils/husky-check-utils" }
husky-print-utils = { path = "../../utils/husky-print-utils" }
wild-utils = { path = "../../utils/husky-wild-utils" }
husky-dev-utils = { path = "../../utils/husky-dev-utils" }
husky-test-utils = { path = "../../utils/husky-test-utils" }
husky-display-utils = { path = "../../utils/husky-display-utils" }
# abstraction
interner = { path = "../../abstraction/interner" }
fold = { path = "../../abstraction/fold" }
vec-like = { path = "../../abstraction/vec-like" }
upcast = { path = "../../abstraction/upcast" }
idx-arena = { path = "../../abstraction/idx-arena" }
map-collect = { path = "../../abstraction/map-collect" }
# syntax
husky-expr-syntax = { path = "../../syntax/husky-expr-syntax" }
husky-file = { path = "../../syntax/husky-file" }
husky-text = { path = "../../syntax/husky-text" }
husky-token = { path = "../../syntax/husky-token" }
husky-entity-syntax = { path = "../../syntax/husky-entity-syntax" }
husky-primitive-literal-syntax = { path = "../../syntax/husky-primitive-literal-syntax" }
husky-entity-kind = { path = "../../syntax/husky-entity-kind" }
husky-atom = { path = "../../syntax/husky-atom" }
husky-defn-head = { path = "../../syntax/husky-defn-head" }
husky-pattern-syntax = { path = "../../syntax/husky-pattern-syntax" }
husky-opn-syntax = { path = "../../syntax/husky-opn-syntax" }
husky-init-syntax = { path = "../../syntax/husky-init-syntax" }
husky-loop-syntax = { path = "../../syntax/husky-loop-syntax" }
# kernel
husky-word = { path = "../../kernel/husky-word" }
husky-entity-route = { path = "../../kernel/husky-entity-route" }
# static
husky-static-defn = { path = "../../static/husky-static-defn" }
# semantics
husky-liason-semantics = { path = "../../semantics/husky-liason-semantics" }
