[package]
name = "husky-toolchain-config"
version.workspace = true
edition = "2021"

[dependencies]
thiserror.workspace = true
semver = "1.0.17"
serde.workspace = true
# abstractions
salsa.workspace = true
# lex
# husky-text-protocol.workspace = true
# husky-toml-token.workspace = true
# kernel
husky-coword.workspace = true
# fs
# husky-toml-ast.workspace = true
# husky-toolchain-config-ast.workspace = true
husky-vfs.workspace = true
# utils
husky-toml-utils.workspace = true

[dev-dependencies]

[features]
test_utils = ["salsa/test_utils"]
